name: Run Script

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas
          python -m pip install matplotlib
          python -m pip install numpy
          python -m pip install python-pptx
          python -m pip install seaborn
          python -m pip install sendgrid
        
      - name: Run script
        run: | 
          python test.py
          python capability_assessment_graphs.py

      - name: Configure git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
      - name: Commit and push changes
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use your secret name
        run: |
          git add .
          git commit -m "Automatically generated PPTX report" -a || echo "No changes to commit"
          git push https://${MY_GITHUB_TOKEN}@github.com/ehlke-hepworth/power-automate.git
  
