name: Run Script

on:
  push:
  repository_dispatch:
    types: [trigger-script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pandas
        python -m pip install matplotlib.pyplot
        python -m pip install numpy
        
    - name: Run script
      run: | 
        python test.py
        python power-automate/capability-assessment.py
