name: Run Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If you have any dependencies, install them here
        pip install -r requirements.txt
    - name: Run script
      run: | 
        python power-automate/test.py
        python power-automate/capability-assessment.py
